### ISSUE TITLE
Minor OSV discrepancy

### ISSUE THREAD

**Issue by oliverchang** [bitnami/vulndb#149]
### Title

Minor OSV discrepancy

### What steps will reproduce the bug?

Current bitnami advisories seem to encode the ecosystem name as "bitnami" (all lowercase).

e.g.

https://github.com/bitnami/vulndb/blob/32679c1954b27ab0a784e6ca8e05ac6404a48db3/data/activemq/BIT-2020-11998.json#L11

### What is the expected behavior?

The ecosystem names in the OSV schema (https://ossf.github.io/osv-schema/#affectedpackage-field) are case sensitive. The ecosystem string should be encoded with an uppercase B. 

e.g.

```
      "package": {
        "ecosystem": "Bitnami",
        "name": "activemq",
        "purl": "pkg:bitnami/activemq"
      },
```

### What do you see instead?

```
      "package": {
        "ecosystem": "bitnami",
        "name": "activemq",
        "purl": "pkg:bitnami/activemq"
      },
```

**Comment by gongomgra** [comment]
Hi @oliverchang,

Thanks for your report! We will update the ecosystem field. I will keep you posted

**Comment by gongomgra** [comment]
Hi @oliverchang,

Just a quick note to let you know that we have updated our database information fixing the ecosystem typo at [PR#151](https://github.com/bitnami/vulndb/pull/151). I'm closing this issue as solved. Do not hesitate to reopen it in case you have any further questions. Thanks!
